// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/promote-first-admin": {
    params: {};
  };
  "/auth/finish": {
    params: {};
  };
  "/auth/twitch": {
    params: {};
  };
  "/billing/success": {
    params: {};
  };
  "/chain-generator": {
    params: {};
  };
  "/cuhz-bot": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/gallery": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin" | "/admin/promote-first-admin" | "/auth/finish" | "/auth/twitch" | "/billing/success" | "/chain-generator" | "/cuhz-bot" | "/dashboard" | "/gallery" | "/pricing" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./admin/page.jsx": {
    id: "admin/page";
    page: "/admin";
  };
  "./admin/promote-first-admin/page.jsx": {
    id: "admin/promote-first-admin/page";
    page: "/admin/promote-first-admin";
  };
  "./auth/finish/page.jsx": {
    id: "auth/finish/page";
    page: "/auth/finish";
  };
  "./auth/twitch/page.jsx": {
    id: "auth/twitch/page";
    page: "/auth/twitch";
  };
  "./billing/success/page.jsx": {
    id: "billing/success/page";
    page: "/billing/success";
  };
  "./chain-generator/page.jsx": {
    id: "chain-generator/page";
    page: "/chain-generator";
  };
  "./cuhz-bot/page.jsx": {
    id: "cuhz-bot/page";
    page: "/cuhz-bot";
  };
  "./dashboard/page.jsx": {
    id: "dashboard/page";
    page: "/dashboard";
  };
  "./gallery/page.jsx": {
    id: "gallery/page";
    page: "/gallery";
  };
  "./pricing/page.jsx": {
    id: "pricing/page";
    page: "/pricing";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "admin/page": typeof import("./src/app/./admin/page.jsx");
  "admin/promote-first-admin/page": typeof import("./src/app/./admin/promote-first-admin/page.jsx");
  "auth/finish/page": typeof import("./src/app/./auth/finish/page.jsx");
  "auth/twitch/page": typeof import("./src/app/./auth/twitch/page.jsx");
  "billing/success/page": typeof import("./src/app/./billing/success/page.jsx");
  "chain-generator/page": typeof import("./src/app/./chain-generator/page.jsx");
  "cuhz-bot/page": typeof import("./src/app/./cuhz-bot/page.jsx");
  "dashboard/page": typeof import("./src/app/./dashboard/page.jsx");
  "gallery/page": typeof import("./src/app/./gallery/page.jsx");
  "pricing/page": typeof import("./src/app/./pricing/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};